### ISSUE TITLE
Can't show image on FullScreen (1200x1900)

### ISSUE THREAD

**Issue by Lure5134** [nospam2k/epson-wireless-projector#1]
If I am showing an image with the size 1200 x 1900 it doens't show up on the beamer.
The beamer just show's a black screen.
I think this has something to do with the Bytes 17, 18 and 19 in the baHeader?
I have converted this code to kotlin, show that I can use this on my phone. But I need to call the connect Function twice to show an Image. If this get's only be called once, I can successfully connect to the projector but it is just black and doesn't show any image.
I haven't changed something, just converted it to Kotlin and I am using a Bitmap with Paint, because the other objects aren't implemented. Could you please help me?

**Comment by nospam2k** [comment]
More than likely this is a problem in my implementation. My projector does support that resolution. I really only put this up so others could build on the code. I haven't done anything with it in years. I'm sorry I don't really have any advise to give you as the project is so old now. I can say that IIRC when you get a black screen it doesn't like the image.

**Comment by Lure5134** [comment]
Okay thanks... But from where you know that you must send a JPEG565 image and so? Have you decompiled the IProjection App or something like that? If yes how can I do it? I really want it to work...

**Comment by nospam2k** [comment]
Everything I know is in the code. I documented the bytes as much as I understood from reverse engineering, packet capture, etc. I know it's a jpeg because the image packet has the prefix of a jpeg. IIRC, I had to do a little messing around to determine the right packet size for the image junks. Make sure the jpeg packets are actually correct. Black screen (again from memory) basically means the jpg is not complete. Read up on jpg format, specifically the header. I think that may be where you are having the issue.

**Comment by nospam2k** [comment]
Have a look here. It may not be complete for larger images.

            // Calc size into special
            int iSize = bImage.length;
            baHeader[17] = (byte) ((iSize) | 0x80);
            baHeader[18] =  (byte) ((iSize >> 7) | 0x80);
            baHeader[19] = (byte) ((iSize >> 14));

**Comment by Lure5134** [comment]
If I am keeping it, how it is actually this works. But it is on the projector small and not full screen. If I am setting a heighter value in the bitmap sizes, that I am sending (incrementing the iImageWidh and iImageHeight) then it is black.

**Comment by nospam2k** [comment]
Sorry that I can't be of any more help. As I mentioned, my projector doesn't support that resolution so I can't go any further.

**Comment by nospam2k** [comment]
Having thought about this a bit more. I suggest you check your projector for acceptable resolutions. I don't think 1200 x 1900 is valid.

**Comment by Lure5134** [comment]
![image](https://user-images.githubusercontent.com/54278236/102284670-d9cef380-3f34-11eb-8531-5735afa8f375.png)

It is 1920 to 1200
But thanks for your help. The project has helped me a lot.

**Comment by Lure5134** [comment]
I have now tested a bit more. The max size of the bitmap for me is 1472x984. This doesn't fill the complete screen. But if I am increasing the height or the width, the screen just keeps black

**Comment by Lure5134** [comment]
But the Image shows at the bottom right. Does it mean, it has an X and an Y offset?
I doesn't have changed something. In the baHeader the offset's are still 0. But could this be the bug?

**Comment by nospam2k** [comment]
As I said, and you rightly pointed out, the calculations for baHeader 17, 18, 19 may not be correct for certain resolutions. I came up with this in searching out, trial and error and stumbling on some similar calculations and honestly, I can't even remember much of what it does. It has been 5 years ago since I've touched it. Just to clarify. I'm no longer working on this and am not even using this projector anymore. I put this info up to hopefully help others. I was going to remove issue reporting but decided to leave it so others could contribute as desired. I think you are on the right track messing with baHeader though.

**Comment by nospam2k** [comment]
One suggestion is to print out what the current 17, 18 and 19 values are and bypass the calculation by hard code changing those numbers for the resolution you are after to get a feel for what those numbers should be. I remember after having a quick look at the code that the technique used by Epson is similar to VNC and I believe that is how I landed on that calculation. I think if you keep looking at my comments over and over and doing some research on VNC packets, you may find the problem. Have a look at different values for 17, 18, 19 at different working resolutions and see if you can find a connection.

**Comment by Lure5134** [comment]
Yes I want to try it but if I am using the IProjection App on Android, then Wireshark only get's the Broadcast and doesn't show the communication. If I am using the IProjection App on my Laptop, I can't find any BaHeader. The App doesn't use it. It sends only the Images and some random stuff😅

**Comment by Lure5134** [comment]
Ok, I have found the bug. If we want to send an image with full hd, we need to set the xOffset to -448 and the y offset to -156. Idk why

**Comment by nospam2k** [comment]
Fantastiic @Hummel37 ! I'm glad you persevered! I will add that as a note to the code.
